version: '3.8'

services:
  luna-back-end:
    container_name: luna-back-end
    build: .  # Usa o diretório atual como contexto
    ports:
      - "8080:8080"
    networks:
      - auth

networks:
  auth:
    driver: bridge